apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: thdq2l36k-java-springboot-gitops
  description: This is GitOps manifest for thdq2l36k-java-springboot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: thdq2l36k-java-springboot
    janus-idp.io/tekton: thdq2l36k-java-springboot
    backstage.io/kubernetes-id: thdq2l36k-java-springboot 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:thdq2l36k-java-springboot
